baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Paul'

[taxonomies]
tag = 'tags'

[params]
# Appearance settings
theme = 'light'

# Intro on main page, content is markdown
homeIntroTitle = 'Hi, Paul here! 👋'
homeIntroContent = """
Welcome to my personal website! Here you can explore my works, including my portfolio and blog.

I enjoy creating web projects and writing blog posts about various topics. Feel free to browse through my latest web projects and read my blog to get insights into my interests and experiences.

"""


# Lists parameters
paginationSize = 5
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/paulus-kelvin-wiranata"

[[params.social]]
name = "instagram"
url = "https://www.instagram.com/paul.uskelvinwiranata/"

[[params.social]]
name = "github"
url = "https://github.com/pauluskelvinwiranata"

[[params.social]]
name = "x"
url = "https://x.com/@KelvinPaul76075"

# Main menu pages
[[params.menu]]
name = "Home"
url = "/"

[[params.menu]]
name = "About"
url = "/about"

[[params.menu]]
name = "Portfolios"
url = "/portfolios"

[[params.menu]]
name = "Posts"
url = "/posts"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"